# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6074cbd13640c2c29cc3d18efa71034513e60f11904dd447d95a0831aae46081e2e3e20eecd4644a7dd9dd1d34bf2e5e6f72711f1aa3c7986c826fff0d2b6304

test:
  secret_key_base: 6a59d05056e1d5161b6d8cb30269d3a75dec06204e9f8d0268a90678c6d165a5e230153f34d0113a8111813f743d8b40583b7eae9749e774d1a49b491621357a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
